### ISSUE TITLE
Add optional parameter "timezone" to `emissions/forecast/current`

### ISSUE THREAD

**Issue by Noordsestern** [bluehands/Carbon-Aware-Computing#2]
I am using the web api to retrieve schedules for my workloads. The timestamp i get back is in my local zone (CEST).

However, most k8s cluster run on UTC which currently is 2 hours apart from CEST. At the moment I would need to convert timestamps, which is a bit inconvenient, since I run the request on command line during a deployment.

It would be super useful, if I could set the timezone in the request.

**Comment by AydinMirMohammadi** [comment]
The data from the [Frauenhofer ISE](https://www.ise.fraunhofer.de/) is in unix timestamp utc. The data provider convert this timestamps into .NET DateTimeOffset and serialize it into json with the offset.
The Carbon SDK does not change the time zone. I just check the entire chain from the Energy Charts API up to the conversion and the SDK with the data in web. All the data is in UTC with the offset notation. 

``` json
[
    {
        "location": "de",
        "windowSize": 5,
        "optimalDataPoints": [
            {
                "timestamp": "2023-09-10T11:45:00+00:00",
                "value": 3.1
            }
        ]
    }
]
```
I don't see where the local zone CEST comes from. Maybe the conversion back from the Web API? Maybe the best would be a direct debugging session. Please drop me a private message.

**Comment by Noordsestern** [comment]
Thanks for the clarification. I had a mixup in my assumptions and timezone readings :see_no_evil: 

All good :+1:
