### ISSUE TITLE
Extend forecast API with more locations

### ISSUE THREAD

**Issue by wielrenner** [bluehands/Carbon-Aware-Computing#5]
Are there any plans to extend the forecast API with more locations like Netherlands?

**Comment by AydinMirMohammadi** [comment]
Of course. No Problem. The Data is supported for the most (I think maybe all) European Countries. To avoid unnecessary processing, I have activated only a few. Did you want more than Netherlands? 
I will activate the others and will drop a message here

**Comment by wielrenner** [comment]
Ideally also Finland, Belgium, since those are low carbon regions around the Netherlands.

I'm trying to convince others we should move out of NL datacenter :)

**Comment by AydinMirMohammadi** [comment]
Add NL, FI & BE to the list activated regions. These countries and the corresponding data center for Azure, GCP & AWS are now available as new "Enum"-Entries in code. Please check and close the issue
